overrides:
  sass-embedded: 1.100.0

allowBuilds:
  "@parcel/watcher": true
  esbuild: true

minimumReleaseAgeExclude:
  - "@quasar/app-vite@3.0.0-beta.33"
  - "@quasar/extras@2.0.0"
  - "@quasar/render-ssr-error@2.2.3"
  - "@quasar/vite-plugin@1.12.0"
  - vue-router@5.1.0
