# This file exists to force pnpm install deps here, regardless of upper workspaces
# https://pnpm.io/settings

allowBuilds:
  electron: true
  electron-winstaller: true

minimumReleaseAgeExclude:
  - 'app-builder-lib@26.15.2'
  - 'dmg-builder@26.15.2'
  - 'electron'
  - 'electron-builder'
  - 'electron-builder-squirrel-windows@26.15.2'
trustLockfile: true
