# This file exists to force pnpm install deps here, regardless of upper workspaces
# https://pnpm.io/settings

allowBuilds:
  electron: true
  electron-winstaller: true

minimumReleaseAge: 0
trustLockfile: true
