# This file exists to force pnpm install deps here, regardless of upper workspaces
# https://pnpm.io/settings

allowBuilds:
  electron: true
  electron-winstaller: true

minimumReleaseAgeExclude:
  - electron
  - electron@42.3.0
  - electron-builder
  - electron@42.3.1
  - app-builder-lib@26.15.2
  - dmg-builder@26.15.2
  - electron-builder-squirrel-windows@26.15.2

trustLockfile: true
